services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: postres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: helpdesk-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petshop
      SPRING_DATASOURCE_USERNAME: postres
      SPRING_DATASOURCE_PASSWORD: postres
    depends_on:
      - postgres

volumes:
  postgres-data:
